core/urls.py
from django.urls import path

from core.views import NewsView, KeyWords, YandexNewsSource, ToggleActiveKey, VKNewsSource

app_name = 'core'
urlpatterns = [
    path('', NewsView.as_view(), name='news'),
    path('key-words/', KeyWords.as_view(), name='key_words'),
    path('yandex-source/', YandexNewsSource.as_view(), name='yandex_source'),
    path('vk-source/', VKNewsSource.as_view(), name='vk_source'),

    # ajax
    path('toggle_active_key/', ToggleActiveKey.as_view(), name='toggle_active_key')
]

news_trigger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('user.urls')),
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user.views import SignUp

app_name = 'user'
urlpatterns = [

    path('register/', SignUp.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')

]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    Model User
    """

    def __str__(self):
        return f'{self.username} - ({self.get_full_name()})'

user/forms.py
from django.forms import ModelForm
from django import forms

from user.models import User


class RegistrationForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']

    def __str__(self):
        return self.name

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

user/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from user.forms import RegistrationForm


class SignUp(generic.CreateView):
    """
    Class-based view for Registration
    """
    form_class = RegistrationForm
    success_url = reverse_lazy('user:login')
    template_name = 'user/signup.html'

user/templates/user/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'user/user.css' %}">
</head>

<body>
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

user/templates/user/home.html
{% extends "user/base.html" %}
{% block title %}Home{% endblock %}



{% block content %}

    {% if user.is_authenticated %}

        Hi {{ user.username }}!



    {% else %}

        <p>You are not logged in</p>

        <a href="{% url 'user:login' %}">login</a>

    {% endif %}

{% endblock %}

user/templates/user/login.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container vh-100">
        <div class="row vh-100">
            <div class="col-lg-6 col-md-12 col-sm-12">
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 d-flex align-items-center">
                <div class="col-10 offset-1 shadow-sm leftReg p-5">
                    <h2><b>Login</b></h2>

                    <form method="post">

                        {% csrf_token %}
                        {{ form|crispy }}

                        <button class="btn btn-outline-primary" type="submit">Login</button>
                        <a class="btn btn-outline-secondary" href="{% url 'user:register' %}">Registration</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/signup.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Registration{% endblock %}

{% block content %}
    <div class="container vh-100">
        <div class="row vh-100">
            <div class="col-lg-6 col-md-12 col-sm-12">
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 d-flex align-items-center ">
                <div class="col-10 offset-1 shadow-sm leftReg p-5">
                    <h2><b>Registration</b></h2>
                    <form method="post">

                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-outline-primary" type="submit">Create account</button>
                        <a class="btn btn-outline-secondary" href="{% url 'user:login' %}">Login</a>
                        <p class="font-weight-lighter my-2">* - required fields</p>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/start_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>