core/urls.py
from django.urls import path

from core.views import NewsView, KeyWords, YandexNewsSource, ToggleActiveKey, VKNewsSource

app_name = 'core'
urlpatterns = [
    path('', NewsView.as_view(), name='news'),
    path('key-words/', KeyWords.as_view(), name='key_words'),
    path('yandex-source/', YandexNewsSource.as_view(), name='yandex_source'),
    path('vk-source/', VKNewsSource.as_view(), name='vk_source'),

    # ajax
    path('toggle_active_key/', ToggleActiveKey.as_view(), name='toggle_active_key')
]

news_trigger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('user.urls')),
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user.views import SignUp

app_name = 'user'
urlpatterns = [

    path('register/', SignUp.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')

]

core/models.py
from datetime import datetime

from django.db import models
from django.db.models import Manager

MAX_LENGTH = 255


class UncheckedYandexNewsItem(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(checked=False)


class YandexNewsTopic(models.Model):
    name = models.CharField(max_length=500, db_index=True)
    rss_url = models.URLField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} - [{self.rss_url}]'

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'rss_url')


class YandexNewsItem(models.Model):
    title = models.CharField(max_length=300)
    link = models.URLField(max_length=350, unique=True)
    pub_date = models.DateTimeField()
    hash = models.CharField(max_length=100, unique=True)
    checked = models.BooleanField(default=False)

    objects = Manager()
    unchecked = UncheckedYandexNewsItem()

    def __str__(self):
        return f'{self.title} [{self.pub_date}] [{self.checked}] [{self.hash}] [{self.link}]'


class TriggerPhrase(models.Model):
    name = models.CharField(max_length=300, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'


class TriggerNews(models.Model):
    YANDEX = 0
    VK = 1
    NEWS_TYPE_CHOICES = (
        (YANDEX, 0),
        (VK, 1)
    )
    POSITIVE = 0
    NEGATIVE = 1
    SKIP = 2
    NEUTRAL = 3
    UNKNOWN = 4
    TONE_TYPE_CHOICES = (
        (POSITIVE, 0),
        (NEGATIVE, 1),
        (SKIP, 2),
        (NEUTRAL, 3),
        (UNKNOWN, 4),
    )
    title = models.CharField(max_length=300)
    article_link = models.URLField()
    last_update = models.DateTimeField(default=datetime.now)
    description = models.TextField(blank=True)
    rate = models.PositiveIntegerField(default=0)
    trigger_word = models.ManyToManyField(TriggerPhrase)
    news_type = models.IntegerField(choices=NEWS_TYPE_CHOICES, default=YANDEX)
    tone_type = models.SmallIntegerField(choices=TONE_TYPE_CHOICES, default=NEUTRAL)
    tone_value = models.FloatField(default=1.0)

    def __str__(self):
        return f'{self.title} [{self.rate}] [type - {self.news_type}]- [{self.article_link}]'

    class Meta:
        ordering = ('-last_update', '-rate')
        verbose_name = 'Trigger news'
        verbose_name_plural = 'Trigger news'


class UncheckedVKPost(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(checked=False)


class VKSource(models.Model):
    name = models.CharField(max_length=MAX_LENGTH)
    vk_id = models.CharField(max_length=32, primary_key=True, unique=True)

    def __str__(self):
        return f'{self.name} - [{self.vk_id}]'

    class Meta:
        ordering = ('name',)


class VKGroup(models.Model):
    vk_id = models.IntegerField(null=True, unique=True)
    name = models.CharField(max_length=MAX_LENGTH)
    description = models.TextField(blank=True, null=True)
    members_count = models.PositiveIntegerField()
    verified = models.BooleanField(default=False)
    site = models.CharField(max_length=MAX_LENGTH, null=True)
    photo_100 = models.CharField(max_length=MAX_LENGTH)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} - [{self.vk_id}]'

    def link(self):
        return f'https://vk.com/public{self.vk_id}'

    class Meta:
        ordering = ('name',)


class VKPost(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    owner = models.ForeignKey(VKGroup, on_delete=models.CASCADE)
    address = models.SlugField(
        max_length=MAX_LENGTH,
        null=False,
        blank=False,
        unique=True
    )
    pub_date = models.DateField()
    text = models.TextField(blank=True, null=True)
    comments = models.PositiveIntegerField()
    likes = models.PositiveIntegerField()
    reposts = models.PositiveSmallIntegerField()
    checked = models.BooleanField(default=False)
    objects = Manager()
    unchecked = UncheckedVKPost()

    def save(self, *args, **kwargs):
        self.address = f'https://vk.com/wall-{self.owner.vk_id}_{self.id}'
        super(VKPost, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-pub_date',)

core/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView, ListView

from core.models import TriggerNews, TriggerPhrase, YandexNewsTopic, VKGroup


# class HomeView(LoginRequiredMixin, TemplateView):
#     """
#     Main page with all main information
#     """
#     template_name = 'core/home.html'
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context_data = super().get_context_data(**kwargs)
#         context_data['main_page'] = True
#         return context_data


class NewsView(LoginRequiredMixin, ListView):
    """
    Main page with all main information
    """
    template_name = 'core/news.html'
    model = TriggerNews
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['news_page'] = True
        return context_data

    def get_queryset(self):
        queryset = TriggerNews.objects.all()
        filter_word = self.request.GET.get('filter_word', None)
        if filter_word:
            queryset = queryset.filter(trigger_word__name=filter_word)

        filter_news_type = self.request.GET.get('filter_news_type', None)
        if filter_news_type:
            queryset = queryset.filter(news_type__in=filter_news_type.split(','))

        return queryset


class KeyWords(LoginRequiredMixin, ListView):
    """
    Page with all key words
    """
    template_name = 'core/key_words.html'
    model = TriggerPhrase
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['key_words_page'] = True
        return context_data


class YandexNewsSource(LoginRequiredMixin, ListView):
    """
    Page with yandex news sources
    """

    template_name = 'core/yandex_news.html'
    model = YandexNewsTopic
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['yandex_source'] = True
        return context_data


class VKNewsSource(LoginRequiredMixin, ListView):
    """
    Page with vk news sources
    """

    template_name = 'core/vk_news.html'
    model = VKGroup
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['vk_source'] = True
        return context_data


class ToggleActiveKey(LoginRequiredMixin, View):
    """
    Toggle trigger word
    """

    def post(self, request):
        if request.is_ajax():
            key_id = request.POST.get('key_id', None)
            key_type = request.POST.get('type', None)
            is_active = request.POST.get('is_active', None)
            keyword = None
            if key_type == 'word':
                keyword = TriggerPhrase.objects.get(id=key_id)
            elif key_type == 'yandex':
                keyword = YandexNewsTopic.objects.get(id=key_id)
            elif key_type == 'vk':
                keyword = VKGroup.objects.get(id=key_id)
            try:
                keyword.is_active = is_active
                keyword.save()
            except AttributeError:
                pass
            data = {'status': 'ok'}
            return HttpResponse(json.dumps(data), content_type='application/json')

core/templates/core/base.html
{% load static %}
<html>
<head>

    <title>
        {% block title %}Home{% endblock %}
    </title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/81c65d2303.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'core/style.css' %}">
    {% block head %}
    {% endblock %}
</head>
<body>

<div id="container">
    {% include 'core/left_navigation_menu.html' %}

    {% block container %}

    {% endblock %}

</div>

</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}
    Главная страница
{% endblock %}
{% block container %}
    {% load humanize %}
    <div class="main shadow" id="main">



    </div>

{% endblock %}

core/templates/core/key_words.html
{% extends 'core/base.html' %}

{% block title %}
    Ключевые слова
{% endblock %}
{% block container %}
    {% load humanize %}
    <div class="main" id="main">

        {% for word in object_list %}
            <div class="shadow p-3 m-4 news-block rounded">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="key-word-{{ word.id }}"
                            {% if word.is_active %} checked=true {% endif %} data-id={{ word.id }}>
                    <label class="form-check-label font-weight-normal mx-2"
                           for="key-word-{{ word.id }}"><a href="{% url 'core:news' %}?filter_word={{ word.name }}">{{ word }}</a></label>
                </div>
            </div>
        {% endfor %}

        <div class="pagination shadow p-4 m-4 pt-3 mt-3 news-block rounded">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="border rounded btn btn-outline-dark">1</a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="border rounded btn btn-outline-dark">previous</a>
                {% endif %}

                <span class="current">
                    <a href="" class="border rounded btn btn-outline-primary">{{ page_obj.number }}</a>
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="border rounded btn btn-outline-dark">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"
                       class="border rounded btn btn-outline-dark">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </span>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            //add ajax stuff
            {% include 'core/includes/ajax_setup.html' %}

            $('.form-check-input').click(function (event) {
                event.stopPropagation();
                const key_word_id = $(this).attr('data-id');
                const is_active = $(this).is(':checked') ? 'True' : 'False';

                const data = {
                    'type': 'word',
                    'key_id': key_word_id,
                    'is_active': is_active,
                };

                $.ajax({
                    url: '{% url 'core:toggle_active_key' %}',
                    method: 'POST',
                    data: data,
                    content_type: 'application/json',
                    type: 'json',
                    success: (data) => console.log(data),
                    error: (data) => console.log(data),
                });


            });
        });


    </script>

{% endblock %}

core/templates/core/left_navigation_menu.html
<div class="leftMenu">
    <div class="leftMenuBlock1">
        <h1 class="p-2">{{ request.user.get_full_name }}</h1>
    </div>
    <div class="LeftMenuBlock2">
{#        <a class="navigation" href="">#}
{#            <div class="leftMenuItem {% if main_page %}selected{% endif %}"><i class="mr-3 fab fa-accusoft"></i>#}
{#                Главная страница#}
{#            </div>#}
{#        </a>#}

        <a class="navigation" href="{% url 'core:news' %}">
            <div class="leftMenuItem {% if news_page %} selected{% endif %}"><i class="mr-3 fas fa-newspaper"></i>
                Новости
            </div>
        </a>


        <a class="navigation" href="{% url 'core:key_words' %}">
            <div class="leftMenuItem {% if key_words_page %} selected{% endif %}"><i class="mr-3 fas fa-th-list"></i>
                Ключевые слова
            </div>
        </a>

{#        <a class="navigation" href="">#}
{#            <div class="leftMenuItem {% if stat_page %} selected {% endif %}"><i class="mr-3 fa fa-line-chart"></i>#}
{#                Статистика#}
{#            </div>#}
{#        </a>#}

    </div>
    <div class="LeftMenuBlock3">
        <a href="{% url 'core:yandex_source' %}">
            <div class="leftMenuItem {% if yandex_source %} selected {% endif %}"><i class="mr-3 fa fa-yahoo"></i>
                Яндекс Новости
            </div>
        </a>

        <a href="{% url 'core:vk_source' %}">
            <div class="leftMenuItem {% if vk_source %} selected {% endif %}"><i class="mr-3 fa fa-vk"></i>
                Вконтакте
            </div>
        </a>
    </div>

    <div class="LeftMenuBlock3">
{#        <a href="">#}
{#            <div class="leftMenuItem {% if settings_page %} selected {% endif %}"><i class="mr-3 fas fa-cog"></i>#}
{#                Настройки#}
{#            </div>#}
{#        </a>#}

        <a href="{% url 'user:logout' %}">
            <div class="leftMenuItem"><i class="mr-3 fas fa-sign-out-alt"></i>
                Выход
            </div>
        </a>
    </div>
</div>

core/templates/core/news.html
{% extends 'core/base.html' %}
{% load static %}
{% load percent %}
{% block title %}
    Главная страница
{% endblock %}
{% block container %}
    {% load humanize %}
    <div class="main" id="main">

        {% for article in object_list %}
            <div class="shadow p-3 m-4 news-block rounded row">
                <div class="col-9">
                    <h4 class="font-weight-normal">{{ article.title }}</h4>
                    <h5><a href="{{ article.article_link }}">Ссылка на статью</a></h5>
                    <p>{{ article.last_update }}</p>
                </div>
                <div class="">
                    <div class="d-flex my-2" style="height: 20px">
                        <p class="{% if article.news_type == 0 %}
                        yandex-circle
                    {% else %}
                        vk-circle
                    {% endif %} mr-2"></p>
                        <p>{% if article.news_type == 0 %}
                            Яндекс новости
                        {% else %}
                            Вконтакте
                        {% endif %} </p>
                    </div>
                    <div class="my-2">
                        {% if article.tone_type == 0 %}
                            <img class="tone-type-icon" src="{% static 'core/icons/positive.png' %}"
                                 alt="Tone type icon">
                            <span>Положительно: {% percent article.tone_value %}%</span>
                        {% elif article.tone_type == 1 %}
                            <img class="tone-type-icon" src="{% static 'core/icons/negative.png' %}"
                                 alt="Tone type icon">
                            <span>Негативно: {% percent article.tone_value %}%</span>
                        {% else %}
                            <img class="tone-type-icon" src="{% static 'core/icons/need_attention.png' %}"
                                 alt="Tone type icon">
                            <span>Требует внимания: {% percent article.tone_value %}%</span>
                        {% endif %}
                    </div>
                    <div >
                        {% for word in article.trigger_word.all %}
                            <span class="trigger-word-tag">{{ word }}</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="pagination shadow p-4 m-4 pt-3 mt-3 news-block rounded">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="border rounded btn btn-outline-dark">1</a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="border rounded btn btn-outline-dark">previous</a>
                {% endif %}

                <span class="current">
                    <a href="" class="border rounded btn btn-outline-primary">{{ page_obj.number }}</a>
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="border rounded btn btn-outline-dark">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"
                       class="border rounded btn btn-outline-dark">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </span>
        </div>
    </div>

    {% include 'core/right_navigation_menu.html' %}
{% endblock %}

core/templates/core/right_navigation_menu.html
<div class="rightMenu">
    <div class="rightMenuBlock1">Настройки новостей</div>
    <form>
        <div class="rightMenuBlock2">

            <div class="rightMenuItem">
                <span class="blue m-2 mb-3"><i class="fas fa-font" style="margin-right:1em;"></i> Источники</span>
                <div class="form-group mt-2" style="padding: 0.6em 0.2em">
                    <div>
                        <p><a class="news_type_text" href="{% url 'core:news' %}?filter_news_type=0">Яндекс Новости</a>
                        </p>
                    </div>
                    <div>
                        <p><a class="news_type_text" href="{% url 'core:news' %}?filter_news_type=1">Вконтакте</a></p>
                    </div>
                    <div>
                        <p><a class="news_type_text" href="{% url 'core:news' %}?filter_news_type=0,1">Все</a></p>
                    </div>
                </div>
            </div>

            <div class="rightMenuItem">
                <span class="blue"><i class="fas fa-clock" style="margin-right:1em;"></i> Время</span>
                <div class="form-group mt-2" style="padding: 0.6em 0.2em">
                    <div>
                        <p><a class="news_type_text" href="{% url 'core:news' %}?order=">Сначала новые</a></p>
                    </div>
                    <div>
                        <p><a class="news_type_text" href="{% url 'core:news' %}?order=">Сначала старые</a></p>
                    </div>
                </div>
            </div>

            <div class="rightMenuItem">
                <span class="blue"><i class="fas fa-exclamation" style="margin-right:1em;"></i> Важность</span>
                <div class="form-group mt-2" style="padding: 0.6em 0.2em">
                    <div>
                        <p><a class="news_type_text" href="{% url 'core:news' %}?priority=">Сначала важные</a></p>
                    </div>
                    <div>
                        <p><a class="news_type_text" href="{% url 'core:news' %}?priority=">Сначала неважные</a></p>
                    </div>
                </div>
            </div>


        </div>
    </form>
</div>

core/templates/core/vk_news.html
{% extends 'core/base.html' %}

{% block title %}
    VK новости
{% endblock %}
{% block container %}
    {% load humanize %}
    <div class="main" id="main">

        {% for source in object_list %}
            <div class="shadow p-3 m-4 news-block rounded">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="key-word-{{ source.id }}"
                            {% if source.is_active %} checked=true {% endif %} data-id={{ source.id }}>

                    <label class="form-check-label font-weight-normal mx-2"
                           for="key-word-{{ source.id }}">
                        <h5>{{ source.name }}</h5>
                        <p>
                            <a href="{{ source.link }}">Ссылка на источник</a>
                        </p></label>
                </div>
            </div>
        {% endfor %}

        <div class="pagination shadow p-4 m-4 pt-3 mt-3 news-block rounded">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="border rounded btn btn-outline-dark">1</a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="border rounded btn btn-outline-dark">previous</a>
                {% endif %}

                <span class="current">
                    <a href="" class="border rounded btn btn-outline-primary">{{ page_obj.number }}</a>
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="border rounded btn btn-outline-dark">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"
                       class="border rounded btn btn-outline-dark">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </span>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            //add ajax stuff
            {% include 'core/includes/ajax_setup.html' %}

            $('.form-check-input').click(function (event) {
                event.stopPropagation();
                const key_word_id = $(this).attr('data-id');
                const is_active = $(this).is(':checked') ? 'True' : 'False';

                const data = {
                    'type': 'vk',
                    'key_id': key_word_id,
                    'is_active': is_active,
                };

                $.ajax({
                    url: '{% url 'core:toggle_active_key' %}',
                    method: 'POST',
                    data: data,
                    content_type: 'application/json',
                    type: 'json',
                    success: (data) => console.log(data),
                    error: (data) => console.log(data),
                });


            });
        });
    </script>
{% endblock %}

core/templates/core/yandex_news.html
{% extends 'core/base.html' %}

{% block title %}
    Яндекс новости
{% endblock %}
{% block container %}
    {% load humanize %}
    <div class="main" id="main">

        {% for source in object_list %}
            <div class="shadow p-3 m-4 news-block rounded">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="key-word-{{ source.id }}"
                            {% if source.is_active %} checked=true {% endif %} data-id={{ source.id }}>

                    <label class="form-check-label font-weight-normal mx-2"
                           for="key-word-{{ source.id }}">
                        <h5>{{ source.name }}</h5>
                        <p>
                            <a href="{{ source.rss_url }}">Ссылка на источник</a>
                        </p></label>
                </div>
            </div>
        {% endfor %}

        <div class="pagination shadow p-4 m-4 pt-3 mt-3 news-block rounded">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="border rounded btn btn-outline-dark">1</a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="border rounded btn btn-outline-dark">previous</a>
                {% endif %}

                <span class="current">
                    <a href="" class="border rounded btn btn-outline-primary">{{ page_obj.number }}</a>
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="border rounded btn btn-outline-dark">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"
                       class="border rounded btn btn-outline-dark">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </span>
        </div>
    </div>

     <script>
        $(document).ready(function () {
            //add ajax stuff
            {% include 'core/includes/ajax_setup.html' %}

            $('.form-check-input').click(function (event) {
                event.stopPropagation();
                const key_word_id = $(this).attr('data-id');
                const is_active = $(this).is(':checked') ? 'True' : 'False';

                const data = {
                    'type': 'yandex',
                    'key_id': key_word_id,
                    'is_active': is_active,
                };

                $.ajax({
                    url: '{% url 'core:toggle_active_key' %}',
                    method: 'POST',
                    data: data,
                    content_type: 'application/json',
                    type: 'json',
                    success: (data) => console.log(data),
                    error: (data) => console.log(data),
                });


            });
        });
    </script>
{% endblock %}